I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/BattleScript.rpy", line 251, in script
    $ target_check()
  File "game/BattleScript.rpy", line 251, in <module>
    $ target_check()
  File "game/BattleScript.rpy", line 56, in target_check
    temp = lvUpSys()
  File "game/BattleScript.rpy", line 50, in lvUpSys
    temp = event_LevelUp([10, 0.5])
NameError: name 'event_LevelUp' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/BattleScript.rpy", line 251, in script
    $ target_check()
  File "/Users/baik-sungkyu/Documents/TowerofBabel/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/baik-sungkyu/Documents/TowerofBabel/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/BattleScript.rpy", line 251, in <module>
    $ target_check()
  File "game/BattleScript.rpy", line 56, in target_check
    temp = lvUpSys()
  File "game/BattleScript.rpy", line 50, in lvUpSys
    temp = event_LevelUp([10, 0.5])
NameError: name 'event_LevelUp' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
Tower Of Babel 1.0
Sun Sep 29 12:41:13 2024
